apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vprodb
  name: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - image: vprocontainers/vprofiledb
        name: vprodb
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: vpro-db-data
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWPORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: db-pass
      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: vpro-db-data
      volumes:
        - name: vpro-db-data
          persistentVolumeClaim:
            claimName: db-pv-claim